/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
const awsmobile = {
  aws_project_region: 'eu-west-1',
  aws_cognito_identity_pool_id:
    'eu-west-1:01bf06b4-7043-4f32-abdc-08708dcc5d77',
  aws_cognito_region: 'eu-west-1',
  aws_user_pools_id: 'eu-west-1_c3auu0aFw',
  aws_user_pools_web_client_id: '237pvl0vm53bojvi78qocvck92',
  oauth: {},
  aws_appsync_graphqlEndpoint:
    'https://awrrfakbqnd2tavcytrrxn4ob4.appsync-api.eu-west-1.amazonaws.com/graphql',
  aws_appsync_region: 'eu-west-1',
  aws_appsync_authenticationType: 'API_KEY',
  aws_appsync_apiKey: 'da2-zil4w5435rfqzbmnyxdsxtirii',
  aws_user_files_s3_bucket: 'adpics02532-dev',
  aws_user_files_s3_bucket_region: 'eu-west-1',
};

export default awsmobile;
